### PR TITLE
Switch to GitHub actions

### PR DESCRIPTION
**Pull request by Fohlen**
This introduces GitHub actions based CI and CD.

### CODE REVIEW

**Comment by Fohlen** [comment]
In the future the CD platform may even automagically build for Windows as well!

**Comment by brandly** [comment]
i haven't used Actions yet. is there more i have to do here or will things just work?

the advantage over Travis is that it's easier to automatically generate releases?

**Comment by brandly** [comment]
if this replaces Travis, we can remove the `.travis.yml`

**Comment by Fohlen** [comment]
I did indeed forget to delete `.travis.yml`. the benefit is mainly that actions are easier to read/write and test than Travis, and also the reports are embedded directly into GitHub instead of using a 3rd party which is a better user experience (IMHO)

**Comment by brandly** [comment]
are things like this `GITHUB_TOKEN` automatically set for me since we don't have to leave the GitHub universe?

i just don't have much time for this project at the moment, and i'm scared of opening a can of worms 🙈

**Comment by Fohlen** [comment]
> are things like this `GITHUB_TOKEN` automatically set for me since we don't have to leave the GitHub universe?
> 
> i just don't have much time for this project at the moment, and i'm scared of opening a can of worms 🙈

Hey, yes the `GITHUB_TOKEN` is automagically provided by GitHub, see [this link](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret) for more info.

Don't stress yourself with maintaining.  Take your time and your contributors will be happy to continue once you're on top of it. Alternatively reach out to some of your established contributors to manage the repo for you in the meantime, if that's an option for you!

All the best from wintery Germany,
Lennard

**Comment by brandly** [comment]
it failed... https://github.com/brandly/Lax/commit/fc05d71d5d9ed47113f21d744934c071a8a7a30e

does this mean tests are no longer run for pull requests?

**Comment by brandly** [comment]
i fixed it, but i was trying to avoid this kinda situation. please be more thorough with PRs or let me know when there's uncertainty.

**Comment by Fohlen** [comment]
@brandly that `jobs` part slipped my attention. Will be more thorough in the future!

**Comment by brandly** [comment]
no prob. CD still failing btw https://github.com/brandly/Lax/runs/382163647

**Comment by brandly** [comment]
we need to specify `asset_content_type: application/zip` but also need to zip things up first, i think.

**Comment by Fohlen** [comment]
@brandly I copied the works from https://github.com/actions/upload-release-asset and wasn't really sure what the application type of `.app` is (MIME-Type) and couldn't find any info either. I believe you can upload arbitrary files on a GitHub release, so zipping is *not* a hard requirement.

**Comment by Fohlen** [comment]
According https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types there is no officially known MIME-Type for it either. So maybe just `application/apple` will fit.

**Comment by brandly** [comment]
[it worked](https://github.com/brandly/Lax/commit/c429578cd0e156714274c4dfdc26a9ebcbfdbbf0) and created [a release](https://github.com/brandly/Lax/releases/tag/untagged-9148d4bdb3ae285cf8f7)! ✨

**Pull request merged**
